import type { ConstellationDefinition } from "./types";

export const SAGITTARIUS: ConstellationDefinition = {
  id: "sagittarius",
  name: "Sagittarius",
  stars: [
    { id: "kaus-australis", x: 0.277, y: 0.6231 },
    { id: "kaus-media", x: 0.243, y: 0.4888 },
    { id: "kaus-borealis", x: 0.318, y: 0.359 },
    { id: "polis", x: 0.166, y: 0.2304 },
    { id: "rukbat", x: 0.92, y: 0.8067 },
    { id: "ascella", x: 0.691, y: 0.4904 },
    { id: "namalsadirah", x: 0.508, y: 0.4052 },
    { id: "nunki", x: 0.612, y: 0.3848 },
    { id: "alnasl", x: 0.08, y: 0.5064 },
    { id: "manubrij", x: 0.713, y: 0.2505 },
    { id: "upsilon", x: 0.897, y: 0.08 },
  ],
  lines: [
    ["kaus-australis", "kaus-media"],
    ["kaus-media", "kaus-borealis"],
    ["kaus-borealis", "polis"],
    ["rukbat", "ascella"],
    ["ascella", "namalsadirah"],
    ["namalsadirah", "kaus-borealis"],
    ["nunki", "namalsadirah"],
    ["namalsadirah", "kaus-media"],
    ["kaus-media", "alnasl"],
    ["alnasl", "kaus-australis"],
    ["kaus-australis", "ascella"],
    ["ascella", "nunki"],
    ["nunki", "manubrij"],
    ["manubrij", "upsilon"],
  ],
};
